### ISSUE TITLE
1.4.1: pep517 build fails

### ISSUE THREAD

**Issue by kloczek** [shibukawa/imagesize_py#54]
Source code from git tag
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting dependencies for wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 4, in <module>
    from imagesize import __version__
ImportError: cannot import name '__version__' from 'imagesize' (unknown location)
```

**Comment by aodag** [comment]
You may not have image/__init__.py.
This file can be found in tar ball downloaded from PyPI, but not commited on github repository.

**Comment by kloczek** [comment]
So why this file is not generated by pep517 buuild?

**Comment by shibukawa** [comment]
Sorry, I pushed missing file and retagged 1.4.1.

**Comment by kloczek** [comment]
Thank you very much 👍 
Just retested and all looks good 😄
